version: "3.9"

services:
  next-dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    command: sh -c "pnpm install && pnpm dev -- --hostname 0.0.0.0"

  next-prod:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production

volumes:
  node_modules:
  pnpm-store:
